### PR TITLE
fix: update prevent flicker on Windows (fixes #274)

### LINKED ISSUE #274: Window flickers instead of hiding when clicking tray [OS: Windows]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description
I expect the app window to get hidden if I click the tray icon a second time (or when app window is already visible).

Looking at the [function](https://github.com/maxogden/menubar/blob/master/src/Menubar.ts#L247) that gets fired on tray click, I can see the problem.

```ts
  private async clicked(
    event?: Electron.KeyboardEvent,
    bounds?: Electron.Rectangle
  ): Promise<void> {
    if (event && (event.shiftKey || event.ctrlKey || event.metaKey)) {
      return this.hideWindow();
    }
    
    // this will always return false
    if (this._browserWindow && this._browserWindow.isVisible()) {
      return this.hideWindow(); <--------------------------- // never fired on windows
    }

    this._cachedBounds = bounds || this._cachedBounds;
    await this.showWindow(this._cachedBounds);
  }
```

`hideWindow()` is never called on tray click because the browserWindow's `blur` event is fired first and it hides the window, so it becomes not visible => which causes the flickering

```
1) user clicks tray while window is already shown
2) focus is lost => "blur" event callback is triggered => hide window
3) clicked is called => window is not visible => show window again (flicker)
```

### Steps to Reproduce the Problem

1. Use Menubar on Windows
2. Click tray to show Window
3. Click tray again to hide it

### Expected Behaviour
App window should get hidden on tray click if window is already visible

### Actual Behaviour
App window flickers

### Specifications

- Menubar version: 8.0.0
- Platform: Windows 10
- Electron version: 8.1.1

### Screen Recording

tGMArSQKda

### Other information
I tried to mess around with `setTimeout` and `isAlwaysOnTop` but I never found a good consistent solution.

Thanks in advance!

### PR DESCRIPTION
**Pull request by beoss**
fixes #274

### CODE REVIEW

**Comment by rwwagner90** [comment]
Any updates on this?

File: src/Menubar.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ import { getWindowPosition } from './util/getWindowPosition';
 export class Menubar extends EventEmitter {
   private _app: Electron.App;
   private _browserWindow?: BrowserWindow;
+  private _blurTimeout: any; // track blur events with timeout
```
Comment (amaurymartiny) [inline src/Menubar.ts:19]:
```suggestion
  private _blurTimeout: NodeJS.Timeout | null = null; // track blur events with timeout
```
